<a href="https://colab.research.google.com/github/mohith2326/pdsas2/blob/main/train.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#removing teh missing values and relacing them with mean,median or mode.question1)
import pandas as pd
data = pd.read_csv('/content/drive/MyDrive/train.csv')
missing_values = data.isnull().sum()
num_cols = ['Year','Kilometers_Driven','Seats','Price',]
for col in num_cols:
    if data[col].dtype in ['float64', 'int64']:
        data[col].fillna(data[col].mean(), inplace=True)
cat_cols = ['Name','Location','Fuel_Type', 'Transmission','Owner_Type','Mileage', 'Engine','Power','New_Price']
for col in cat_cols:
    if data[col].dtype == 'object':
        data[col].fillna(data[col].mode()[0], inplace=True)
data.dropna(subset=['Price'], inplace=True)
missing_values_after = data.isnull().sum()
data.to_csv('cleaned_data.csv', index=False)
cleaned_data = pd.read_csv('cleaned_data.csv')
cleaned_data

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
0,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,4.78 Lakh,12.50
1,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,13 km/kg,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.50
2,3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,4.78 Lakh,6.00
3,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2 kmpl,1968 CC,140.8 bhp,5.0,4.78 Lakh,17.74
4,6,Nissan Micra Diesel XV,Jaipur,2013,86999,Diesel,Manual,First,23.08 kmpl,1461 CC,63.1 bhp,5.0,4.78 Lakh,3.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5842,6014,Maruti Swift VDI,Delhi,2014,27365,Diesel,Manual,First,28.4 kmpl,1248 CC,74 bhp,5.0,7.88 Lakh,4.75
5843,6015,Hyundai Xcent 1.1 CRDi S,Jaipur,2015,100000,Diesel,Manual,First,24.4 kmpl,1120 CC,71 bhp,5.0,4.78 Lakh,4.00
5844,6016,Mahindra Xylo D4 BSIV,Jaipur,2012,55000,Diesel,Manual,Second,14.0 kmpl,2498 CC,112 bhp,8.0,4.78 Lakh,2.90
5845,6017,Maruti Wagon R VXI,Kolkata,2013,46000,Petrol,Manual,First,18.9 kmpl,998 CC,67.1 bhp,5.0,4.78 Lakh,2.65
5846,6018,Chevrolet Beat Diesel,Hyderabad,2011,47000,Diesel,Manual,First,25.44 kmpl,936 CC,57.6 bhp,5.0,4.78 Lakh,2.50

In [ ]:
print(cleaned_data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5847 entries, 0 to 5846
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         5847 non-null   int64
 1   Name               5847 non-null   object
 2   Location           5847 non-null   object
 3   Year               5847 non-null   int64
 4   Kilometers_Driven  5847 non-null   int64
 5   Fuel_Type          5847 non-null   object
 6   Transmission       5847 non-null   object
 7   Owner_Type         5847 non-null   object
 8   Mileage            5847 non-null   object
 9   Engine             5847 non-null   object
 10  Power              5847 non-null   object
 11  Seats              5847 non-null   float64
 12  New_Price          5847 non-null   object
 13  Price              5847 non-null   float64
dtypes: float64(2), int64(3), object(9)
memory usage: 639.6+ KB
None

In [ ]:
#removing the str and keeping only int.remove values like cc,bhp,lakh and keep the numeric values as it is question2)
import pandas as pd
import re
def extract_numeric(text):
    matches = re.findall(r"[-+]?\d*\.\d+|\d+", str(text))
    if matches:
        return float(matches[0])
    return None
def clean_and_convert_columns(data, columns_to_clean):
    for col in columns_to_clean:
        data[col] = data[col].apply(extract_numeric)
    data['Engine'] = data['Engine'].astype(int)

columns_to_clean = ['Mileage', 'Engine', 'Power', 'New_Price']

clean_and_convert_columns(cleaned_data, columns_to_clean)

cleaned_data.head()

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
0,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67,1582,126.20,5.0,4.78,12.50
1,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,13.00,1199,88.70,5.0,8.61,4.50
2,3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77,1248,88.76,7.0,4.78,6.00
3,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.20,1968,140.80,5.0,4.78,17.74
4,6,Nissan Micra Diesel XV,Jaipur,2013,86999,Diesel,Manual,First,23.08,1461,63.10,5.0,4.78,3.50

In [ ]:
#changing fuel_type and Transmission in to numeric encoded values
import pandas as pd


cleaned_data = pd.get_dummies(cleaned_data, columns=['Fuel_Type', 'Transmission'])


cleaned_data.head()

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price,Fuel_Type_Diesel,Fuel_Type_Electric,Fuel_Type_Petrol,Transmission_Automatic,Transmission_Manual
0,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,First,19.67,1582,126.20,5.0,4.78,12.50,1,0,0,0,1
1,2,Honda Jazz V,Chennai,2011,46000,First,13.00,1199,88.70,5.0,8.61,4.50,0,0,1,0,1
2,3,Maruti Ertiga VDI,Chennai,2012,87000,First,20.77,1248,88.76,7.0,4.78,6.00,1,0,0,0,1
3,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Second,15.20,1968,140.80,5.0,4.78,17.74,1,0,0,1,0
4,6,Nissan Micra Diesel XV,Jaipur,2013,86999,First,23.08,1461,63.10,5.0,4.78,3.50,1,0,0,0,1

In [ ]:
#creating a column as car_Age
from datetime import datetime
current_year = datetime.now().year

cleaned_data['Car_Age'] = current_year - cleaned_data['Year']

cleaned_data.head()

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price,Fuel_Type_Diesel,Fuel_Type_Electric,Fuel_Type_Petrol,Transmission_Automatic,Transmission_Manual,Car_Age
0,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,First,19.67,1582,126.20,5.0,4.78,12.50,1,0,0,0,1,8
1,2,Honda Jazz V,Chennai,2011,46000,First,13.00,1199,88.70,5.0,8.61,4.50,0,0,1,0,1,12
2,3,Maruti Ertiga VDI,Chennai,2012,87000,First,20.77,1248,88.76,7.0,4.78,6.00,1,0,0,0,1,11
3,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Second,15.20,1968,140.80,5.0,4.78,17.74,1,0,0,1,0,10
4,6,Nissan Micra Diesel XV,Jaipur,2013,86999,First,23.08,1461,63.10,5.0,4.78,3.50,1,0,0,0,1,10